### ISSUE TITLE
Buttons Swapped

### ISSUE THREAD

**Issue by ghost** [ttsuki/ProconXInputTE#1]
It's not a virtual xbox 360 controller like the application specifies. It's a virtual Pro Controller. I already have my muscle memory for how the button are on xbox/playstation. Why would you swap the buttons? At least have an option for button customization or something. This is an annoying roadblock from allowing me to use this program.

**Comment by ttsuki** [comment]
Thank you for issuing issue!

It is implemented at [v0.5.0](https://github.com/ttsuki/ProconXInputTE/releases/tag/v0.5.0)
