### ISSUE TITLE
Virus in your .exe files

### ISSUE THREAD

**Issue by cabiamdos** [ttsuki/ProconXInputTE#3]
According to this, your files are full of virus
![image](https://user-images.githubusercontent.com/82284393/209746299-a0abef73-0a8b-45f0-b037-d7594d748438.png)

What do you have to say about this? 
Thanks

**Comment by ttsuki** [comment]
Thank you for reporting.

I think it is false positive.

I just re-built a binary and released as `v0.5.1`: 
https://github.com/ttsuki/ProconXInputTE/releases

(but `v0.5.1` binaries are also flagged as malware: 
[virustotal:e1fc7901e5d351b06b51fc8400c8534144493a4bc00f2518103049f191ef0989](https://www.virustotal.com/gui/file/e1fc7901e5d351b06b51fc8400c8534144493a4bc00f2518103049f191ef0989)

If you are concerned about it, please build binary yourself from source code.
